[package]
name = "listener"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
